### ISSUE TITLE
Error on large files - crc64

### ISSUE THREAD

**Issue by jimcruse** [hansij66/securecopy#1]
Please see my email for file crccp.script for the script log
Of the error message

**Comment by hansij66** [comment]
Issue was found on a Rasp Pi (32 bit)
Related to limitations of a 32 bit OS.
Issue is fixed in V2.0.7 and tested on 32bit X86 debian
To be tested by submitter on Raspberry Pi

**Comment by hansij66** [comment]
V2.0.7 verified with on Raspberry Pi and OK; issue resolved

**Comment by hansij66** [comment]
Credits to Jim Cruse for verification and debugging.

**Comment by jimcruse** [comment]
The build version I'm running maybe Sid rather than buster
  berr2
<https://drive.google.com/file/d/1plzSUywd6-NiEKnimow6XC0b-mZSNhYI/view?usp=drivesdk>
