### ISSUE TITLE
Build failure Debian buster

### ISSUE THREAD

**Issue by jimcruse** [hansij66/securecopy#2]
Here ya go, I just loaded a new Debian buster and tried to rebuild as before and it keeps failing, ive got the script file I'll send it you directly viA Gmail 
Thanks 
Jim
crusejim@gmail.com

**Comment by hansij66** [comment]
Jim, don;t have access to your google drive.

Debian SID is very unstable. Did you try to build de stock core-utils -
that is atleast a prerequisite.

Cheers
Hans

**Comment by hansij66** [comment]
I am closing issue
- I did not get access to build output on google drive, I cannot inspect what is going on
- In a second email, I believe it was build on Debian sid, which I did not test
==> basic condition: try to build core-utils-8.32 and if that fails, first try to fix this.
