### ISSUE TITLE
Xattr.h not found


### ISSUE THREAD

**Issue by jimcruse** [hansij66/securecopy#3]
I still have problems compiling on Debian buster with gcc-8, 
Xattr/xattr.h is not found, but it appears to be sys/xattr.h

**Comment by hansij66** [comment]
Hi Jim
1) try to build core-utils as is (8.32), then there is no dependency with what I have done; That is a pre-requisite
2) It is possible that you miss a few dependencies - look at:
  https://packages.debian.org/source/stable/coreutils
This shows you the dependencies which you require to build core utils 8.30; 

My guess that one of these are missing:
adep: libattr1-dev [linux-any]
adep: libacl1-dev [linux-any]

**Comment by hansij66** [comment]
I replied in github for a suggestion

**Comment by jimcruse** [comment]
I actually found it in your crcsum.c

**Comment by hansij66** [comment]
Hi Jim

I looked in the Dockerfile, which I once did setup to test 32bit version.
Based on a stock docker debian image, I had to include below.

I am pretty sure that  libattr1-dev  is the missing on your system.


    apt-get install -y --no-install-recommends -qq \
        procps \
        git \
        build-essential \
        automake-1.15 \
        texinfo \
        ca-certificates \
        wget \
        libattr1-dev \
        nano

**Comment by jimcruse** [comment]
You are correct, I installed libattr1-dev and it worked,
Since you already apt-get automake in the build-secure-copy script why not
add this dependency


Jim
P.s. please fuse.mount.rclone does not support extended attributes and your
crccp reports a fault even though it did do the copy and checked the crc it
just couldn't save it....

**Comment by jimcruse** [comment]
i have fixed the build with libattr1-dev

**Comment by hansij66** [comment]
Hi Jim, I added the dependency yesterday; it is committed. Thanks!

I will look at the fuse fs, whether/how to improve on error handling.

Cheers
Hans

**Comment by jimcruse** [comment]
Thank you I'll check it out,

**Comment by jimcruse** [comment]
I confirmed the new build worked

**Comment by jimcruse** [comment]
ive confirmed the xattr issue gives a Warning on ntfs fuse-3g

   since ntfs is supposed to roll into core linux,

   think now would be

**Comment by hansij66** [comment]
Hi Jim

I have not found (yet) an elegant way to test for xattr capabilities. There
are less elegant ways, but that makes it slow(er) and potentially give
other issues.

BR
Hans
