### ISSUE TITLE
Update to enable retry on CRC fail 

### ISSUE THREAD

**Issue by jimcruse** [hansij66/securecopy#4]
I would like have the option available to retry the copy if the CRC doesn't match...

**Comment by hansij66** [comment]
Hi Jim

Have you experienced cases where CRC fails first time, and succeeds second
time? I would feel pretty concerned about destination media, as it should
not fail; if it would fail that often on first attempt and succeeds on a
second attempt, I wonder what is root cause.

Can you let me know your specific experience?

Thanks
Hans

**Comment by jimcruse** [comment]
It seems to happen a lot on a fuse filesystem (NTFS 3g or exfat)

**Comment by hansij66** [comment]
Jim,
I have done a a little research (not very thorough) on fuse, and also based on my past experience with fuse; Fuse FS's should be reliable in the first place; if you run in many issues, I think you should invest why it happens. My only issue I have had in past is with sshfs, when network was intermittent.

Also, keeping the philosophy of linux/unix that tools should do one thing, but very well, I don't want to add this functionality to crccp/crcmv; what it does do well: crccp flags when copy is not successful, and that should be a rare occurrence in the first place.

Last, coreutils cp & mv don't implement a retry (there are more reasons why a copy can fail), hence there is not a design implemented, where I can piggy back on.

If it is still important to you, an option for you is to create a wrapper (bash, python,...) around crccp taking its output and in case of failure start a retry.

Very last, afaik, linux provides native kernel ntfs support (no fuse required), and in latest kernel, also exFAT has been added. That might also help you
